### ISSUE TITLE
Savegame file not existent

### ISSUE THREAD

**Issue by bonsaibauer** [hihouhou/docker-enshrouded#1]
I was able to start the Docker normally with:

docker build -t enshrouded-server:v1.0 .

docker run -p 15636:15636/udp \
  -p 15637:15637/udp \
  -v /var/www/gameserver/enshrouded-server/savegame:/savegame \
  -d --name enshrouded-server-instance --restart always enshrouded-server:v1.0
and
sudo chown -R 1000:1000 /var/www/gameserver/enshrouded-server/savegame
sudo chmod -R 775 /var/www/gameserver/enshrouded-server/savegame

However, it doesn't work, a save file is never created in the savegame folder.

**Comment by hihouhou** [comment]
```ls -l <MYPATH>/enshrouded/data/savegame/
total 1808
-rw-r--r-- 1 XXXXXX XXXXXX 922610 Feb 26 18:29 3ad85aea
-rw-r--r-- 1 XXXXXX XXXXXX 922610 Feb 26 18:29 3ad85aea.backup
```
it works, did you configure something about /savegame in enshrouded_server.json (saveDirectory)  ?

**Comment by hihouhou** [comment]
/savegame != ./savegame
next time do a fork... copy paste like you did on https://github.com/bonsaibauer/enshrouded-server2/blob/main/Dockerfile ...
